# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.

# ifeq ($(config),debug)
# override config := Debug
# endif
# ifeq ($(config),release)
# override config := Release
# endif
# ifeq ($(config),Debug)
# CPPFLAGS ?= -DDEBUG
# CFLAGS ?= -g -O0
# CXXFLAGS ?= -g -O0
# LDFLAGS ?= -g
# else ifeq ($(config),Release)
# CPPFLAGS ?= -DNDEBUG
# CFLAGS = -Wall -std=c99 -g
# CXXFLAGS ?= -O2
# else ifneq (,$(config))
# $(warning Unknown configuration "$(config)")
# endif

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := mingw32-gcc
CXX := mingw32-g++

CFLAGS = -Wall -std=c99 -g

# The directory for the build files, may be overridden on make command line.
builddir = obj

all: Brikz

rebuild: clean all

run: Brikz
	Brikz

Brikz: $(builddir)/Brikz_Program.o $(builddir)/Brikz_MainMenu.o $(builddir)/Brikz_Brikz.o $(builddir)/Brikz_levelMaker.o $(builddir)/Brikz_levels.o 
	$(CXX) -o $@ $(LDFLAGS) $(builddir)/Brikz_Program.o $(builddir)/Brikz_MainMenu.o $(builddir)/Brikz_Brikz.o $(builddir)/Brikz_levelMaker.o $(builddir)/Brikz_levels.o -L../../SDL/32/lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL_gfx
	

$(builddir)/Brikz_Program.o: src/Program.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -I../../SDL/32/include src/Program.c

$(builddir)/Brikz_MainMenu.o: src/MainMenu.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -I../../SDL/32/include src/MainMenu.c

$(builddir)/Brikz_Brikz.o: src/Brikz.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -I../../SDL/32/include src/Brikz.c
	
	
$(builddir)/Brikz_levelMaker.o: src/levelMaker.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -I../../SDL/32/include src/levelMaker.c

$(builddir)/Brikz_levels.o: src/levels.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -I../../SDL/32/include src/levels.c

clean:
	cd $(builddir)
	del /s *.o
	del /s *.d
	cd ..
	del Brikz.exe
	
.PHONY: all rebuild clean run

# Dependencies tracking:
-include *.d
